<!-- Svelte component consists of 3 parts (all optional)
1. Script tag
2. Markup
3. Style tag - only scoped to this component via hashes generated by Svelte

Svelte will generate a Hash for each component you create, so that the style tags only apply to this component. 
-->

<script>
    let name = 'Svelte'; // variable declaration defined here will be accessible in markup
    let src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/1200px-Svelte_Logo.svg";
    let string= 'Some string with <strong>html</strong>';
</script>


<h1> Hello {name.toLowerCase()}</h1>
<!-- <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/1200px-Svelte_Logo.svg.png" alt="Svelte Logo" width="200" height="200"> -->
<img {src} alt={`Some text ${name}`} /> <!-- this is not necessary in svelte -->
<img {src} alt="Some text {name}" /> <!-- you can directly add the variable to the string -->
{@html string} <!-- you can parse the html. Be careful. Need to trust source bc of potential malicious scripts-->
<style>
    h1 {
        color: red;
    }
</style>